[package]
name = "etherscan-api-rs"
version = "0.1.0"
authors = ["vsmysle <kyrylo.voronchenko@gmail.com>"]

[dependencies]
lazy_static 	= "1.0"
reqwest 	= "1.0"
serde		= "1.0"
serde_derive	= "1.0"
serde_json	= "1.0"

